"""Tests for the distributed-job orchestration logic.

A real distributed run cannot happen in CI: there is no Slurm scheduler to
execute the generated sbatch script (so the two-launch handoff never fires),
no GPU, and the second launch (``accelerate launch ... -m ...``) lives *inside*
that script rather than in the pickled task. ``submission.process_job`` just
unpickles the task and calls it directly, bypassing all of that.

What these tests cover instead is slurmic's own distributed *orchestration* —
the part that can actually regress — without a cluster or GPU:

1. The sbatch script generated by the monkey-patch in
   ``SubmititDistributedCommandContext`` (and that the patch is reverted).
2. The distributed-env math in ``PyTorchDistributedTask.set_up_dist_env`` /
   ``command`` (driven by faked ``SLURM_*`` env vars).
3. The sentinel-driven dispatch that makes the second launch run the wrapped
   function inline instead of re-submitting.
"""

import contextlib
import os
import typing as tp

from submitit import SlurmExecutor
from submitit.core import utils

from slurmic import SlurmConfig
from slurmic.core._slurm_context import SubmititDistributedCommandContext
from slurmic.task import PyTorchDistributedTask

# Reuse the mock harness, the distributed config builder, and the demo function
# from the main test module so the two stay in sync.
from tests.test_slurm import distributed_fn, get_slurm_config, mocked_slurm


@contextlib.contextmanager
def fake_slurm_job_env(**overrides: str) -> tp.Iterator[None]:
    """Pretend the current process is a task inside a 2-node x 2-task Slurm job.

    ``submitit.helpers.TorchDistributedEnvironment`` (used by ``set_up_dist_env``)
    reads these variables; ``SUBMITIT_EXECUTOR`` is what tells submitit it is a
    Slurm job environment. Override any of them per-test (e.g. ``SLURM_PROCID``).
    """
    env = {
        "SUBMITIT_EXECUTOR": "slurm",
        "SLURM_JOB_ID": "424242",
        "SLURM_JOB_NODELIST": "node[1-2]",
        "SLURM_NTASKS": "4",
        "SLURM_JOB_NUM_NODES": "2",
        "SLURM_PROCID": "0",
        "SLURM_LOCALID": "0",
        "SLURM_NODEID": "0",
    }
    env.update(overrides)
    # set_up_dist_env() calls TorchDistributedEnvironment().export(), which writes
    # these into os.environ; environment_variables won't restore keys it didn't set,
    # so clean them up here to keep tests isolated.
    exported_by_torch = (
        "MASTER_ADDR",
        "MASTER_PORT",
        "RANK",
        "WORLD_SIZE",
        "LOCAL_RANK",
        "LOCAL_WORLD_SIZE",
    )
    with utils.environment_variables(**env):
        try:
            yield
        finally:
            for key in exported_by_torch:
                os.environ.pop(key, None)


# --------------------------------------------------------------------------- #
# Layer 1: the generated sbatch script (the monkey-patch).
# --------------------------------------------------------------------------- #
def test_distributed_sbatch_script_injects_second_launch(tmp_path):
    """Submitting a distributed job in slurm mode must produce an sbatch script
    that, after the submitit submit step, exports the sentinel, sources the
    distributed env script, and runs the formatted second-launch command."""
    original_command_str = SlurmExecutor._submitit_command_str

    with mocked_slurm():
        slurm_settings = get_slurm_config(f"{tmp_path}/outputs/", is_distributed=True)
        job = distributed_fn[slurm_settings](1, k=1)
        script = next(job.paths.folder.glob("*_submission.sh")).read_text()

    # The submitit submit step itself is still present...
    assert "-u -m submitit.core._submit" in script
    # ...followed by the injected slurmic second launch.
    assert "export SLURMIC_SLURM_HAS_BEEN_SET_UP=1" in script
    assert "source" in script
    assert "slurmic_distributed_env.sh" in script
    assert "accelerate launch" in script
    assert "-m tests.test_slurm" in script
    # At submission time the placeholders resolve to the shell vars defined by
    # the (runtime-generated) env script, not literal numbers.
    assert "--num_processes $slurmic_num_processes" in script
    assert "--machine_rank $slurmic_machine_rank" in script

    # The patch must be reverted once submission is done.
    assert SlurmExecutor._submitit_command_str is original_command_str


def test_distributed_command_context_is_noop_outside_slurm():
    """The command patch must only apply in slurm mode; other modes are left
    untouched so the function is run/launched directly."""
    original_command_str = SlurmExecutor._submitit_command_str

    config = SlurmConfig(
        mode="local",
        job_name="test",
        partition="p",
        use_distributed_env=True,
        processes_per_task=2,
        distributed_launch_command="launch -m tests.test_slurm",
    )
    task = PyTorchDistributedTask(config.distributed_launch_command, [], config)

    context = SubmititDistributedCommandContext(config, task)
    with context:
        assert context.is_patched is False
        assert SlurmExecutor._submitit_command_str is original_command_str
    assert SlurmExecutor._submitit_command_str is original_command_str


# --------------------------------------------------------------------------- #
# Layer 2: the distributed-env math.
# --------------------------------------------------------------------------- #
def test_set_up_dist_env_computes_distributed_args():
    """Given a faked Slurm job env, set_up_dist_env derives the process/machine
    layout and command() fills the launch-command placeholders accordingly."""
    config = SlurmConfig(
        mode="slurm",
        job_name="test",
        partition="p",
        num_of_node=2,
        tasks_per_node=2,
        processes_per_task=3,
        gpus_per_task=0,
        use_distributed_env=True,
        distributed_launch_command=(
            "launch --np {num_processes} --nm {num_machines} --rank {machine_rank} "
            "--ip {main_process_ip} --port {main_process_port}"
        ),
    )

    # This task is global rank 2 of a 4-task, 2-node job.
    with fake_slurm_job_env(SLURM_PROCID="2"):
        task = PyTorchDistributedTask(
            config.distributed_launch_command, ["--foo", "bar"], config, verbose=False
        )
        dist_args, dist_env = task.set_up_dist_env()
        command = task.command()

    # num_processes = tasks_per_node * processes_per_task * num_of_node
    assert dist_args.num_processes == 2 * 3 * 2
    assert dist_args.num_machines == 2
    # machine_rank = global_rank // tasks_per_node
    assert dist_args.machine_rank == 2 // 2
    # master addr is the first hostname parsed from SLURM_JOB_NODELIST="node[1-2]".
    assert dist_args.main_process_ip == "node1"
    assert dist_env.world_size == 4

    assert "--np 12" in command
    assert "--nm 2" in command
    assert "--rank 1" in command
    assert "--ip node1" in command
    # The original argv is reconstructed and appended after the launch command.
    assert command.endswith("--foo bar")


def test_export_bash_writes_sourceable_env_script(tmp_path):
    """export_bash writes a script that exports each distributed arg as a
    slurmic_-prefixed shell variable (the values the sbatch script sources)."""
    with fake_slurm_job_env(SLURM_PROCID="0"):
        config = SlurmConfig(
            mode="slurm",
            job_name="test",
            partition="p",
            num_of_node=2,
            tasks_per_node=2,
            processes_per_task=3,
            use_distributed_env=True,
            distributed_launch_command="launch {num_processes}",
        )
        task = PyTorchDistributedTask(config.distributed_launch_command, [], config)
        dist_args, _ = task.set_up_dist_env()
        dist_args.export_bash(str(tmp_path))

    script = (tmp_path / "slurmic_distributed_env.sh").read_text()
    assert "export slurmic_num_processes=12" in script
    assert "export slurmic_num_machines=2" in script
    assert "export slurmic_main_process_ip=node1" in script


# --------------------------------------------------------------------------- #
# Layer 3: the sentinel-driven second launch.
# --------------------------------------------------------------------------- #
def test_second_launch_runs_function_inline(tmp_path):
    """When SLURMIC_SLURM_HAS_BEEN_SET_UP is set (i.e. we are inside the second
    launch), the function is called directly and returns its raw value instead
    of being re-submitted as a Job."""
    slurm_settings = get_slurm_config(f"{tmp_path}/outputs/", is_distributed=True)
    fn = distributed_fn[slurm_settings]

    # Without the sentinel a distributed slurm job would be submitted.
    assert fn.engine._should_be_submitted_to_executor is True

    # With the sentinel set, the call short-circuits to the wrapped function.
    with utils.environment_variables(SLURMIC_SLURM_HAS_BEEN_SET_UP="1"):
        assert fn.engine._should_be_submitted_to_executor is False
        result = fn(7, k=9)

    assert result == ((7,), {"k": 9})
